{% set version = "2.6.0" %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
  url: https://github.com/tensorflow/estimator/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 947705c60c50da0b4a8ceec1bc058aaf6bf567a7efdcd50d5173ebf6bafcf30f

build:
  number: 0
  noarch: python
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng
    - tensorflow

requirements:
  build:
    ## Needs tensorflow to build, but conda complains that it depends on itself -- see build.sh
    # - tensorflow
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - bazel
    - setuptools
    - wheel
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py >=0.7.0
    - astor >=0.6.0
    - gast >=0.2.0
    - numpy >=1.19
    - six >=1.10.0
    - protobuf >=3.6.1
    - termcolor >=1.1.0
    - wrapt >=1.11.1

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tensorflow/estimator
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming.

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - kyleabeauchamp
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
    - jschueller
