{% set version = "2.4.0" %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
  url: https://github.com/tensorflow/estimator/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e6ea12014c3d8c89a81ace95f8f8b7c39ffcd3e4e4626709e4aee0010eefd962

build:
  number: 1
  noarch: python
  ignore_run_exports:
    - libgcc-ng
    - libstdcxx-ng
    - tensorflow

requirements:
  build:
    ## it actually does need tensorflow to build, but conda complains that it depends on itself
    # - tensorflow-estimator
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}    
    - python
    - mamba
    - bazel
    - setuptools
    - wheel
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.19
    - wrapt >=1.11.1

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tensorflow/estimator
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming.

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - kyleabeauchamp
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
    - jschueller
