{% set version = "2.0.0" %}
{% set build_number = 0 %}

package:
  name: tensorflow-estimator
  version: {{ version }}

source:
   url: https://files.pythonhosted.org/packages/95/00/5e6cdf86190a70d7382d320b2b04e4ff0f8191a37d90a422a2f8ff0705bb/tensorflow_estimator-{{version}}-py2.py3-none-any.whl
   sha256: 54fdfe8712d54627579bc6d524ced43bbd57042cb2ce411bdf2ae46b29a772da

build:
  number: {{ build_number }}
  skip : True  # [py27]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorflow_estimator-{{version}}-py2.py3-none-any.whl
  
requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy  >=1.16.0, <2.0

test:
  imports:
    - numpy  # NB: can't import tensorflow on CI due to glibc compat issues.  

about:
  home: https://github.com/tensorflow/estimator
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming."

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - dougalsutherland
    - kyleabeauchamp
    - jjhelmus
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
    - roccqqck
